version: '3'
services:

# The mysql containers 
  mysql:
    image: mysql:5.7
    volumes:
      - "$GVV_MYSQL_DIR:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: db_password

  # A container to manage the mysql database
  myadmin:
    hostname: phpmyadmin
    domainname: phpmyadmin.flub78.fr
    # depends_on:
      # - gvv
    image: phpmyadmin/phpmyadmin
    links:
      - "mysql:db"
    ports:
      - "$PORT_PHPMYADMIN:80"
    restart: always
    
  # An apache php container
  apache:
    hostname: apache
    image: flub78/apache-php
    ports:
      - "$PORT_HTTP:80"
      - "$PORT_HTTPS:443"      
    volumes:
      - "$GVV_HOME:/var/www/html/"
    links:
      - "mysql:db"
    restart: always
    